lut_config:
  softmax:
    bf16:
      - path: 'yz8_softmax_bf16_freq900_lut.csv'
        prepaared: false
        main: true
        use_for_model: true
        use_for_kernel: true
        require_annotation: false
    fp32:
      - path: 'yz8_softmax_fp32_freq900_lut.csv'
        prepaared: false
        main: true
        use_for_model: true
        use_for_kernel: true
        require_annotation: false
  layernorm:
    bf16:
      - path: 'yz8_layernorm_bf16_freq900_lut.csv'
        prepaared: false
        main: true
        use_for_model: true
        use_for_kernel: true
        require_annotation: false
    fp32:
      - path: 'yz8_layernorm_fp32_freq900_lut.csv'
        prepaared: false
        main: true
        use_for_model: true
        use_for_kernel: true
        require_annotation: false     
  gemm:
    tc:
      bf16_bf16:
        - path: 'yz8_gemmex_bf16bf16_freq900_noflush_lut_v2.csv'
          prepared: false
          main: true
          use_for_model: true
          use_for_kernel: true
          require_annotation: false
    cuda:
      fp32_fp32: 
        - path: 'yz8_sgemm_freq900_noflush_lut_v2.csv'
          prepared: false
          main: true
          use_for_model: true
          use_for_kernel: true
          require_annotation: false
  conv2d:
    tc:
      bf16_bf16:
        - path: 'yz8_conv2d_bf16_freq900_lut.csv'
          prepared: false
          main: true
          use_for_model: true
          use_for_kernel: true
          require_annotation: false
  elementwise:
    - path: 'yz8_misc_elementwise_freq900_lut.csv'
      prepared: false
      main: true
      use_for_model: true
      use_for_kernel: true
      require_annotation: false
  flashattention_v2:
    bf16:
      - path: 'yz8_flashattention_freq900_lut.csv'
        prepared: false
        main: true
        use_for_model: true
        use_for_kernel: true
        require_annotation: false